models/User.php
<?php

namespace webvimark\modules\UserManagement\models;

use webvimark\helpers\LittleBigHelper;
use webvimark\helpers\Singleton;
use webvimark\modules\UserManagement\components\AuthHelper;
use webvimark\modules\UserManagement\components\UserIdentity;
use webvimark\modules\UserManagement\models\rbacDB\Role;
use webvimark\modules\UserManagement\models\rbacDB\Route;
use webvimark\modules\UserManagement\UserManagementModule;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $email
 * @property integer $email_confirmed
 * @property integer $ldap_user
 * @property string $auth_key
 * @property string $password_hash
 * @property string $confirmation_token
 * @property string $bind_to_ip
 * @property string $registration_ip
 * @property integer $status
 * @property integer $superadmin
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $user_dn
 */
class User extends UserIdentity {

  const STATUS_ACTIVE = 1;
  const STATUS_INACTIVE = 0;
  const STATUS_BANNED = -1;

  /**
   * @var string
   */
  public $gridRoleSearch;

  /**
   * @var string
   */
  public $password;

  /**
   * @var string
   */
  public $repeat_password;

  /**
   * Store result in singleton to prevent multiple db requests with multiple calls
   *
   * @param bool $fromSingleton
   *
   * @return static
   */
  public static function getCurrentUser($fromSingleton = true) {
    if (!$fromSingleton) {
      return static::findOne(Yii::$app->user->id);
    }

    $user = Singleton::getData('__currentUser');

    if (!$user) {
      $user = static::findOne(Yii::$app->user->id);

      Singleton::setData('__currentUser', $user);
    }

    return $user;
  }

  /**
   * Assign role to user
   *
   * @param int  $userId
   * @param string $roleName
   *
   * @return bool
   */
  public static function assignRole($userId, $roleName) {
    try {
      Yii::$app->db->createCommand()
          ->insert(Yii::$app->getModule('user-management')->auth_assignment_table, [
            'user_id' => $userId,
            'item_name' => $roleName,
            'created_at' => time(),
          ])->execute();

      AuthHelper::invalidatePermissions();

      return true;
    }
    catch (\Exception $e) {
      return false;
    }
  }

  /**
   * Revoke role from user
   *
   * @param int    $userId
   * @param string $roleName
   *
   * @return bool
   */
  public static function revokeRole($userId, $roleName) {
    $result = Yii::$app->db->createCommand()
            ->delete(Yii::$app->getModule('user-management')->auth_assignment_table, ['user_id' => $userId, 'item_name' => $roleName])
            ->execute() > 0;

    if ($result) {
      AuthHelper::invalidatePermissions();
    }

    return $result;
  }

  /**
   * @param string|array $roles
   * @param bool         $superAdminAllowed
   *
   * @return bool
   */
  public static function hasRole($roles, $superAdminAllowed = true) {
    if ($superAdminAllowed AND Yii::$app->user->isSuperadmin) {
      return true;
    }
    $roles = (array) $roles;

    AuthHelper::ensurePermissionsUpToDate();

    return array_intersect($roles, Yii::$app->session->get(AuthHelper::SESSION_PREFIX_ROLES, [])) !== [];
  }

  /**
   * @param string $permission
   * @param bool   $superAdminAllowed
   *
   * @return bool
   */
  public static function hasPermission($permission, $superAdminAllowed = true) {
    if ($superAdminAllowed AND Yii::$app->user->isSuperadmin) {
      return true;
    }

    AuthHelper::ensurePermissionsUpToDate();

    return in_array($permission, Yii::$app->session->get(AuthHelper::SESSION_PREFIX_PERMISSIONS, []));
  }

  /**
   * Useful for Menu widget
   *
   * <example>
   * 	...
   * 		[ 'label'=>'Some label', 'url'=>['/site/index'], 'visible'=>User::canRoute(['/site/index']) ]
   * 	...
   * </example>
   *
   * @param string|array $route
   * @param bool         $superAdminAllowed
   *
   * @return bool
   */
  public static function canRoute($route, $superAdminAllowed = true) {
    if ($superAdminAllowed AND Yii::$app->user->isSuperadmin) {
      return true;
    }

    $baseRoute = AuthHelper::unifyRoute($route);

    if (Route::isFreeAccess($baseRoute)) {
      return true;
    }

    AuthHelper::ensurePermissionsUpToDate();

    return Route::isRouteAllowed($baseRoute, Yii::$app->session->get(AuthHelper::SESSION_PREFIX_ROUTES, []));
  }

  /**
   * getStatusList
   * @return array
   */
  public static function getStatusList() {
    return array(
      self::STATUS_ACTIVE => UserManagementModule::t('back', 'Active'),
      self::STATUS_INACTIVE => UserManagementModule::t('back', 'Inactive'),
      self::STATUS_BANNED => UserManagementModule::t('back', 'Banned'),
    );
  }

  /**
   * getStatusValue
   *
   * @param string $val
   *
   * @return string
   */
  public static function getStatusValue($val) {
    $ar = self::getStatusList();

    return isset($ar[$val]) ? $ar[$val] : $val;
  }

  /**
   * @inheritdoc
   */
  public static function tableName() {
    return Yii::$app->getModule('user-management')->user_table;
  }

  /**
   * @inheritdoc
   */
  public function behaviors() {
    return [
      TimestampBehavior::className(),
    ];
  }

  /**
   * @inheritdoc
   */
  public function rules() {
    return [
      ['username', 'required'],
      ['username', 'unique'],
      ['username', 'trim'],
      [['status', 'email_confirmed', 'ldap_user'], 'integer'],
      ['email', 'email'],
      ['email', 'validateEmailConfirmedUnique'],
      ['bind_to_ip', 'validateBindToIp'],
      ['bind_to_ip', 'trim'],
      ['bind_to_ip', 'string', 'max' => 255],
      ['password', 'required', 'on' => ['newUser', 'changePassword']],
      ['password', 'string', 'max' => 255, 'on' => ['newUser', 'changePassword']],
      ['password', 'trim', 'on' => ['newUser', 'changePassword']],
      ['repeat_password', 'required', 'on' => ['newUser', 'changePassword']],
      ['repeat_password', 'compare', 'compareAttribute' => 'password'],
    ];
  }

  /**
   * Check that there is no such confirmed E-mail in the system
   */
  public function validateEmailConfirmedUnique() {
    if ($this->email) {
      $exists = User::findOne([
            'email' => $this->email,
            'email_confirmed' => 1,
      ]);

      if ($exists AND $exists->id != $this->id) {
        $this->addError('email', UserManagementModule::t('front', 'This E-mail already exists'));
      }
    }
  }

  /**
   * Validate bind_to_ip attr to be in correct format
   */
  public function validateBindToIp() {
    if ($this->bind_to_ip) {
      $ips = explode(',', $this->bind_to_ip);

      foreach ($ips as $ip) {
        if (!filter_var(trim($ip), FILTER_VALIDATE_IP)) {
          $this->addError('bind_to_ip', UserManagementModule::t('back', "Wrong format. Enter valid IPs separated by comma"));
        }
      }
    }
  }

  /**
   * @return array
   */
  public function attributeLabels() {
    return [
      'id' => 'ID',
      'username' => UserManagementModule::t('back', 'Login'),
      'superadmin' => UserManagementModule::t('back', 'Superadmin'),
      'confirmation_token' => 'Confirmation Token',
      'registration_ip' => UserManagementModule::t('back', 'Registration IP'),
      'bind_to_ip' => UserManagementModule::t('back', 'Bind to IP'),
      'status' => UserManagementModule::t('back', 'Status'),
      'gridRoleSearch' => UserManagementModule::t('back', 'Roles'),
      'created_at' => UserManagementModule::t('back', 'Created'),
      'updated_at' => UserManagementModule::t('back', 'Updated'),
      'password' => UserManagementModule::t('back', 'Password'),
      'repeat_password' => UserManagementModule::t('back', 'Repeat password'),
      'email_confirmed' => UserManagementModule::t('back', 'E-mail confirmed'),
      'ldap_user' => UserManagementModule::t('back', 'LDAP-User'),
      'email' => 'E-mail',
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getRoles() {
    return $this->hasMany(Role::className(), ['name' => 'item_name'])
            ->viaTable(Yii::$app->getModule('user-management')->auth_assignment_table, ['user_id' => 'id']);
  }

  /**
   * Make sure user will not deactivate himself and superadmin could not demote himself
   * Also don't let non-superadmin edit superadmin
   *
   * @inheritdoc
   */
  public function beforeSave($insert) {
    if ($insert) {
      if (php_sapi_name() != 'cli') {
        $this->registration_ip = LittleBigHelper::getRealIp();
      }
      $this->generateAuthKey();
    }
    else {
      // Console doesn't have Yii::$app->user, so we skip it for console
      if (php_sapi_name() != 'cli') {
        if (Yii::$app->user->id == $this->id) {
          // Make sure user will not deactivate himself
          $this->status = static::STATUS_ACTIVE;

          // Superadmin could not demote himself
          if (Yii::$app->user->isSuperadmin AND $this->superadmin != 1) {
            $this->superadmin = 1;
          }
        }

        // Don't let non-superadmin edit superadmin
        if (!Yii::$app->user->isSuperadmin AND $this->oldAttributes['superadmin'] == 1) {
          return false;
        }
      }
    }

    // If password has been set, than create password hash
    if ($this->password) {
      $this->setPassword($this->password);
    }

    return parent::beforeSave($insert);
  }

  /**
   * Don't let delete yourself and don't let non-superadmin delete superadmin
   *
   * @inheritdoc
   */
  public function beforeDelete() {
    // Console doesn't have Yii::$app->user, so we skip it for console
    if (php_sapi_name() != 'cli') {
      // Don't let delete yourself
      if (Yii::$app->user->id == $this->id) {
        return false;
      }

      // Don't let non-superadmin delete superadmin
      if (!Yii::$app->user->isSuperadmin AND $this->superadmin == 1) {
        return false;
      }
    }

controllers/LdapController.php
<?php

namespace webvimark\modules\UserManagement\controllers;

use webvimark\components\BaseController;
use webvimark\modules\UserManagement\models\User;
use webvimark\modules\UserManagement\UserManagementModule;
use Yii;
use yii\web\Response;
use yii\widgets\ActiveForm;
use webvimark\modules\UserManagement\sistemas\ldapHelper;
use webvimark\modules\UserManagement\sistemas\ldapConfig;


class LdapController extends BaseController {

	public $freeAccessActions = ['get-user','get-users'];

	public $propiedades = ['gidnumber','uidnumber','sn','givenname','mail','pager']; // dn siempre es devuelto
	public function actionGetUser() {

		Yii::$app->response->format = Response::FORMAT_JSON;

        $ldap_servers = Yii::$app->user->ldapServer;
        $ldap_domains = Yii::$app->user->ldapDomain;

        $ldap_connection_established = false;

        $username = Yii::$app->request->get('username');

        if (is_null($username)) {
        	//http://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm        	
        	throw new \yii\web\HttpException(422, 'Invalid username');
        }
        foreach ($ldap_servers as $ldap_server) {

          foreach ($ldap_domains as $ldap_domain) {
            $auth_user = '';
			$minciHelper = new ldapHelper(
                new ldapConfig(
                  ['server' => $ldap_server, 
                  'domain' => $ldap_domain])
            );            

			$ldapUser = $minciHelper->buscarUsuario($username);
			if (!is_null($ldapUser)) {
				if ($ldapUser->get('count') >= 1) {
					$arr = [];
					foreach ($this->propiedades as $propiedad) {
						$arr[$propiedad] = $ldapUser->get($propiedad);
					}
					return $arr;
				}
			}
          }
        }

        return NULL;
	}
	public function actionGetUsers() {


        $ldap_servers = Yii::$app->user->ldapServer;
        $ldap_domains = Yii::$app->user->ldapDomain;

        $ldap_connection_established = false;

        $username = Yii::$app->request->get('username');

        if (is_null($username)) {
        	//http://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm        	
        	throw new \yii\web\HttpException(422, 'Invalid username');
        }

        foreach ($ldap_servers as $ldap_server) {

          foreach ($ldap_domains as $ldap_domain) {
            $auth_user = '';
			$minciHelper = new ldapHelper(
                new ldapConfig(
                  ['server' => $ldap_server, 
                  'domain' => $ldap_domain])
            );            

			$ldapUser = $minciHelper->buscarUsuarioNombre($username);
			if (!is_null($ldapUser)) {
				Yii::$app->response->format = Response::FORMAT_JSON;
				return $ldapUser;
			}
          }
        }

        return NULL;

	}

}

controllers/UserController.php
<?php

namespace webvimark\modules\UserManagement\controllers;

use webvimark\components\AdminDefaultController;
use Yii;
use webvimark\modules\UserManagement\models\User;
use webvimark\modules\UserManagement\models\search\UserSearch;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends AdminDefaultController
{
	/**
	 * @var User
	 */
	public $modelClass = 'webvimark\modules\UserManagement\models\User';

	/**
	 * @var UserSearch
	 */
	public $modelSearchClass = 'webvimark\modules\UserManagement\models\search\UserSearch';

	/**
	 * @return mixed|string|\yii\web\Response
	 */
	public function actionCreate()
	{
		$model = new User(['scenario'=>'newUser']);

		if ( $model->load(Yii::$app->request->post()) && $model->save() )
		{
			return $this->redirect(['view',	'id' => $model->id]);
		}

		return $this->renderIsAjax('create', compact('model'));
	}

	/**
	 * @param int $id User ID
	 *
	 * @throws \yii\web\NotFoundHttpException
	 * @return string
	 */
	public function actionChangePassword($id)
	{
		$model = User::findOne($id);

		if ( !$model )
		{
			throw new NotFoundHttpException('User not found');
		}

		$model->scenario = 'changePassword';

		if ( $model->load(Yii::$app->request->post()) && $model->save() )
		{
			return $this->redirect(['view',	'id' => $model->id]);
		}

		return $this->renderIsAjax('changePassword', compact('model'));
	}

}

views/user/_form.php
<?php

use webvimark\modules\UserManagement\models\User;
use webvimark\modules\UserManagement\UserManagementModule;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use webvimark\extensions\BootstrapSwitch\BootstrapSwitch;

/*$bundles = Yii::$app->view->assetManager->bundles;
!ddd($bundles);*/

/**
 * @var yii\web\View $this
 * @var webvimark\modules\UserManagement\models\User $model
 * @var yii\bootstrap\ActiveForm $form
 */
?>


<div class="user-form">

    <?php
    $form = ActiveForm::begin([
          'id' => 'user',
          'layout' => 'horizontal',
          'validateOnBlur' => false,
    ]);
    ?>

    <?=
        $form->field($model->loadDefaultValues(), 'status')
        ->dropDownList(User::getStatusList())
    ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => 255, 'autocomplete' => 'off']) ?>

    <?php if ($model->isNewRecord): ?>

      <?= $form->field($model, 'password')->passwordInput(['maxlength' => 255, 'autocomplete' => 'off']) ?>

      <?= $form->field($model, 'repeat_password')->passwordInput(['maxlength' => 255, 'autocomplete' => 'off']) ?>
    <?php endif; ?>


    <?php if (User::hasPermission('bindUserToIp')): ?>

      <?=
          $form->field($model, 'bind_to_ip')
          ->textInput(['maxlength' => 255])
          ->hint(UserManagementModule::t('back', 'For example: 123.34.56.78, 168.111.192.12'))
      ?>

    <?php endif; ?>

    <?php if (User::hasPermission('editUserEmail')): ?>

      <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>
      <?= $form->field($model, 'email_confirmed')->checkbox() ?>
      <?= $form->field($model, 'ldap_user')->checkbox() ?>
    <?php endif; ?>


    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?php if ($model->isNewRecord): ?>
              <?=
              Html::submitButton(
                  '<span class="glyphicon glyphicon-plus-sign"></span> ' . UserManagementModule::t('back', 'Create'), ['class' => 'btn btn-success']
              )
              ?>
            <?php else: ?>
              <?=
              Html::submitButton(
                  '<span class="glyphicon glyphicon-ok"></span> ' . UserManagementModule::t('back', 'Save'), ['class' => 'btn btn-primary']
              )
              ?>
            <?php endif; ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php BootstrapSwitch::widget() ?>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var webvimark\modules\UserManagement\models\search\UserSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'superadmin') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'login') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'password_hash') ?>

    <?php // echo $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'confirmation_token') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/changePassword.php
<?php

use webvimark\modules\UserManagement\UserManagementModule;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var webvimark\modules\UserManagement\models\User $model
 */

$this->title = UserManagementModule::t('back', 'Changing password for user: ') . ' ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => UserManagementModule::t('back', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = UserManagementModule::t('back', 'Changing password');
?>
<div class="user-update">

	<h2 class="lte-hide-title"><?= $this->title ?></h2>

	<div class="panel panel-default">
		<div class="panel-body">

			<div class="user-form">

				<?php $form = ActiveForm::begin([
					'id'=>'user',
					'layout'=>'horizontal',
				]); ?>

				<?= $form->field($model, 'password')->passwordInput(['maxlength' => 255, 'autocomplete'=>'off']) ?>

				<?= $form->field($model, 'repeat_password')->passwordInput(['maxlength' => 255, 'autocomplete'=>'off']) ?>


				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
						<?php if ( $model->isNewRecord ): ?>
							<?= Html::submitButton(
								'<span class="glyphicon glyphicon-plus-sign"></span> ' . UserManagementModule::t('back', 'Create'),
								['class' => 'btn btn-success']
							) ?>
						<?php else: ?>
							<?= Html::submitButton(
								'<span class="glyphicon glyphicon-ok"></span> ' . UserManagementModule::t('back', 'Save'),
								['class' => 'btn btn-primary']
							) ?>
						<?php endif; ?>
					</div>
				</div>

				<?php ActiveForm::end(); ?>

			</div>
		</div>
	</div>

</div>

views/user/create.php
<?php

use webvimark\modules\UserManagement\UserManagementModule;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var webvimark\modules\UserManagement\models\User $model
 */



class CreateCustomAsset extends \yii\web\AssetBundle {

  public $sourcePath = '@vendor/sistemasmippci/user-management/js';
  public $depends = [
        'yii\web\YiiAsset',
        'yii\web\JqueryAsset',
        'yii\bootstrap\BootstrapAsset',
    ];  
    public $js = [
    	'create-user.js',
    	'jquery.easyModal.js'
    ];
}
CreateCustomAsset::register($this);

$this->title = UserManagementModule::t('back', 'User creation');
$this->params['breadcrumbs'][] = ['label' => UserManagementModule::t('back', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;


?>
<div class="user-create">

	<h2 class="lte-hide-title"><?= $this->title ?></h2>

	<div class="panel panel-default">
		<div class="panel-body row">
			<div class="user-form">
				<div class="form-group field-user-search">
					<label class='control-label col-sm-8'>Search LDAP user</label>
					<div class='col-sm-2'>
						<input id='search-ldap' name='search-ldap' list="usuarios" size="40" placeholder="escriba el nombre del usuario (o apellido)" />
						<datalist id="usuarios">
						</datalist>
					</div>
				</div>
			</div>
		</div>
		<div class="panel-body">
			<?= $this->render('_form', compact('model')) ?>
		</div>
	</div>

</div>
<script>
var apiUrl = '<?= \yii\helpers\Url::to(['ldap/get-users']); ?>';
</script>

views/user/index.php
<?php

use webvimark\modules\UserManagement\components\GhostHtml;
use webvimark\modules\UserManagement\models\rbacDB\Role;
use webvimark\modules\UserManagement\models\User;
use webvimark\modules\UserManagement\UserManagementModule;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;
use webvimark\extensions\GridBulkActions\GridBulkActions;
use webvimark\extensions\GridPageSize\GridPageSize;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var webvimark\modules\UserManagement\models\search\UserSearch $searchModel
 */
$this->title = UserManagementModule::t('back', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h2 class="lte-hide-title"><?= $this->title ?></h2>

    <div class="panel panel-default">
        <div class="panel-body">

            <div class="row">
                <div class="col-sm-6">
                    <p>
                        <?=
                        GhostHtml::a(
                            '<span class="glyphicon glyphicon-plus-sign"></span> ' . UserManagementModule::t('back', 'Create'), ['/user-management/user/create'], ['class' => 'btn btn-success']
                        )
                        ?>
                    </p>
                </div>

                <div class="col-sm-6 text-right">
                    <?= GridPageSize::widget(['pjaxId' => 'user-grid-pjax']) ?>
                </div>
            </div>


            <?php
            Pjax::begin([
              'id' => 'user-grid-pjax',
            ])
            ?>

            <?=
            GridView::widget([
              'id' => 'user-grid',
              'dataProvider' => $dataProvider,
              'pager' => [
                'options' => ['class' => 'pagination pagination-sm'],
                'hideOnSinglePage' => true,
                'lastPageLabel' => '>>',
                'firstPageLabel' => '<<',
              ],
              'filterModel' => $searchModel,
              'layout' => '{items}<div class="row"><div class="col-sm-8">{pager}</div><div class="col-sm-4 text-right">{summary}' . GridBulkActions::widget(['gridId' => 'user-grid']) . '</div></div>',
              'columns' => [
                ['class' => 'yii\grid\SerialColumn', 'options' => ['style' => 'width:10px']],
                [
                  'class' => 'webvimark\components\StatusColumn',
                  'attribute' => 'superadmin',
                  'visible' => Yii::$app->user->isSuperadmin,
                ],
                [
                  'attribute' => 'username',
                  'value' => function(User $model) {
                    return Html::a($model->username, ['view', 'id' => $model->id], ['data-pjax' => 0]);
                  },
                      'format' => 'raw',
                    ],
                    [
                      'attribute' => 'email',
                      'format' => 'raw',
                      'visible' => User::hasPermission('viewUserEmail'),
                    ],
                    [
                      'class' => 'webvimark\components\StatusColumn',
                      'attribute' => 'email_confirmed',
                      'visible' => User::hasPermission('viewUserEmail'),
                    ],
                    [
                      'class' => 'webvimark\components\StatusColumn',
                      'attribute' => 'ldap_user',
                      'visible' => User::hasPermission('viewUserLdap'),
                    ],
                    [
                      'attribute' => 'gridRoleSearch',
                      'filter' => ArrayHelper::map(Role::getAvailableRoles(Yii::$app->user->isSuperAdmin), 'name', 'description'),
                      'value' => function(User $model) {
                        return implode(', ', ArrayHelper::map($model->roles, 'name', 'description'));
                      },
                      'format' => 'raw',
                      'visible' => User::hasPermission('viewUserRoles'),
                    ],
                    [
                      'attribute' => 'registration_ip',
                      'value' => function(User $model) {
                        return Html::a($model->registration_ip, "http://ipinfo.io/" . $model->registration_ip, ["target" => "_blank"]);
                      },
                          'format' => 'raw',
                          'visible' => User::hasPermission('viewRegistrationIp'),
                        ],
                        [
                          'value' => function(User $model) {
                            return GhostHtml::a(
                                    UserManagementModule::t('back', 'Roles and permissions'), ['/user-management/user-permission/set', 'id' => $model->id], ['class' => 'btn btn-sm btn-primary', 'data-pjax' => 0]);
                          },
                              'format' => 'raw',
                              'visible' => User::canRoute('/user-management/user-permission/set'),
                              'options' => [
                                'width' => '10px',
                              ],
                            ],
                            [
                              'value' => function(User $model) {
                                return GhostHtml::a(
                                        UserManagementModule::t('back', 'Change password'), ['change-password', 'id' => $model->id], ['class' => 'btn btn-sm btn-default', 'data-pjax' => 0]);
                              },
                                  'format' => 'raw',
                                  'options' => [
                                    'width' => '10px',
                                  ],
                                ],
                                [
                                  'class' => 'webvimark\components\StatusColumn',
                                  'attribute' => 'status',
                                  'optionsArray' => [
                                    [User::STATUS_ACTIVE, UserManagementModule::t('back', 'Active'), 'success'],
                                    [User::STATUS_INACTIVE, UserManagementModule::t('back', 'Inactive'), 'warning'],
                                    [User::STATUS_BANNED, UserManagementModule::t('back', 'Banned'), 'danger'],
                                  ],
                                ],
                                ['class' => 'yii\grid\CheckboxColumn', 'options' => ['style' => 'width:10px']],
                                [
                                  'class' => 'yii\grid\ActionColumn',
                                  'contentOptions' => ['style' => 'width:70px; text-align:center;'],
                                ],
                              ],
                            ]);
                            ?>

                            <?php Pjax::end() ?>

        </div>
    </div>
</div>

views/user/update.php
<?php

use webvimark\modules\UserManagement\models\User;
use webvimark\extensions\BootstrapSwitch\BootstrapSwitch;
use webvimark\modules\UserManagement\UserManagementModule;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var webvimark\modules\UserManagement\models\User $model
 */

$this->title = UserManagementModule::t('back', 'Editing user: ') . ' ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => UserManagementModule::t('back', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = UserManagementModule::t('back', 'Editing');
?>
<div class="user-update">

	<h2 class="lte-hide-title"><?= $this->title ?></h2>

	<div class="panel panel-default">
		<div class="panel-body">

			<?= $this->render('_form', compact('model')) ?>
		</div>
	</div>

</div>